spring:
  thymeleaf:
    prefix: classpath:/templates/

  # Static resources reloading during development
  resources:
    static-locations: classpath:/static/

  data:
    mongodb:
      host: ubuntu20-lts
      port: 27017
      database: iroha
  file-image-path: /home/julian/projs/scrapyd/file_image