spring:
  # Templates reloading during development
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false

  # Static resources reloading during development
  resources:
    static-locations: file:src/main/resources/static/
  #  cache-period: 0

  # just for passing "mvn package", will be replaced
  # if we use "mvn package -Dspring.profiles.active=prod"
  file-image-path: /XXX
